# Generated by Django 2.1.7 on 2019-03-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=models.TextField(help_text='In-quotation and comma-separated list'),
        ),
        migrations.AlterField(
            model_name='product',
            name='random',
            field=models.BooleanField(help_text='Ignore variant if not found'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(blank=True, help_text='Specific colour, size, etc', max_length=30),
        ),
    ]
