# Generated by Django 2.1.7 on 2019-03-03 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_add_help_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
    ]
